# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm install
      working-directory: ./frontend
    - name: Build frontend
      run: npm run build --if-present
      working-directory: ./frontend
    - name: Upload bundled files
      uses: actions/upload-artifact@v3
      with:
        name: frontend-bundled
        path: ./frontend/dist

    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: memory-box-poapper
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
